// Reads src/style.css and writes src/generated-style.ts, exporting the CSS
// as a plain string constant.
//
// Why this exists: embedding a stylesheet as a JS string via a "raw" import
// (e.g. `import css from "./style.css?raw"`) is handled differently by every
// bundler. Vite understands the `?raw` suffix natively; esbuild/tsup does
// not (it only recognizes loader overrides keyed on the real file
// extension, so `?raw` never matches and esbuild silently falls back to
// treating the import as a normal stylesheet asset). Since this package is
// built with tsup for publishing but also loaded straight from source by
// Vite in the example app (see example/vite.config.ts, which aliases
// "button-carousel" directly to ../src/index.ts), any bundler-specific
// import syntax breaks one of the two. Generating a plain .ts file with no
// special import syntax sidesteps the mismatch entirely — it's just a
// string constant, so every bundler (and plain tsc/node) handles it
// identically.
//
// Run automatically before every build/dev/example:dev script (see
// package.json). src/generated-style.ts is gitignored; edit src/style.css
// and re-run this script (or a build script that calls it) to regenerate.

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath, URL } from "node:url";

const cssPath = fileURLToPath(new URL("../src/style.css", import.meta.url));
const outPath = fileURLToPath(new URL("../src/generated-style.ts", import.meta.url));

const css = readFileSync(cssPath, "utf8");

const output =
  "// AUTO-GENERATED by scripts/generate-css.mjs from src/style.css.\n" +
  "// Do not edit this file directly — edit src/style.css instead.\n" +
  `export const cssText: string = ${JSON.stringify(css)};\n`;

writeFileSync(outPath, output);

console.log(`generate-css: wrote ${outPath} from ${cssPath} (${css.length} chars)`);
